name: Temporary Dev Branch Build

on:
  push:
    branches: [ dev ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Add MSBuild to Path
      uses: microsoft/setup-msbuild@v1.0.2

    # Setup 7z
    - name: Setup 7-zip for archiving
      uses: FilUnderscore/7z-win-action@v1

    - name: Build project files
      run: MSBuild.exe Source\PersistentRimWorlds\PersistentRimWorlds.csproj /p:Configuration=Release
      
    - name: Zip files for install
      run: 7z a PersistentRimWorlds.zip About/ Assemblies/ Defs/ Languages/ Patches/ Sounds/ Textures/
